/*
!!! ATTENTION !!!
THIS FILE HAS BEEN AUTO-GENERATED
DO NOT EDIT THIS FILE
*/

// Imports 
import { AppConfig, api as axios } from '@config/hirovo-config'; 
import { ApiService } from '@services/ApiService';

// Custom Types 
type Guid = string; 
type Double = number;
type Decimal = number;
type Int64 = number;
type Int32 = number;
type int = number;
type long = number;
type __ERROR_TYPE_NOT_HANDLED__ = number;

// Settings...

export namespace HirovoAPI {

	export namespace Enums {

		export enum XSortingDirection {
			Ascending = 0,
			Descending = 1,
		}

		export enum HirovoJobType {
			FullTime = 0,
			PartTime = 1,
			Freelance = 2,
		}

		export enum HirovoJobStatus {
			Active = 0,
			Closed = 1,
			Filled = 2,
		}

		export enum SubscriptionPlan {
			Free = 0,
			Trial = 1,
			Standard = 2,
			Corporate = 3,
		}

		export enum SocialPostType {
			Text = 0,
			JobShare = 1,
			ForumShare = 2,
			Repost = 3,
		}

		export enum SocialGroupType {
			Public = 0,
			Private = 1,
		}

		export enum GroupMemberRole {
			Member = 0,
			Admin = 1,
		}

		export enum ReviewerType {
			Employer = 0,
			Worker = 1,
		}

		export enum ReferralType {
			EmployerToWorker = 0,
			WorkerToEmployer = 1,
		}

		export enum ProfileViewSource {
			Search = 0,
			JobApplication = 1,
			Recommendation = 2,
			Direct = 3,
		}

		export enum MentionSourceType {
			SocialPost = 0,
			SocialPostComment = 1,
			ForumPost = 2,
			ForumComment = 3,
		}

		export enum SwipeDirection {
			Left = 0,
			Right = 1,
			Up = 2,
		}

		export enum JobReportReason {
			Spam = 0,
			Inappropriate = 1,
			Misleading = 2,
			Duplicate = 3,
			Scam = 4,
			Other = 5,
		}

		export enum JobReportStatus {
			Pending = 0,
			Reviewed = 1,
			Resolved = 2,
			Dismissed = 3,
		}

		export enum ApplicationStatus {
			Pending = 0,
			Accepted = 1,
			Rejected = 2,
			Cancelled = 3,
		}

		export enum InviteStatus {
			Active = 0,
			Used = 1,
			Expired = 2,
		}

		export enum VoteType {
			Upvote = 0,
			Downvote = 1,
		}

		export enum AchievementCategory {
			Profile = 0,
			Application = 1,
			Social = 2,
			Streak = 3,
			Milestone = 4,
		}

	}

	export namespace Workers {

		export namespace ProfileCompletionScore {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/ProfileCompletionScore';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalScore: number;
				sections: IProfileSection[];
			}
			export interface IProfileSection {
				name: string;
				score: number;
				isCompleted: boolean;
				missingFields: string[];
			}
		}

		export namespace Pick {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				fullName: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				description: string;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isAvailable: boolean;
				fullName: string;
				bucketId: string;
				coverPictureUrl: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				companyId?: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isAvailable?: boolean;
				displayName: string;
				description: string;
				bucketId: string;
			}
		}

		export namespace UpdateProfile {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/UpdateProfile';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				description: string;
				bucketId: string;
				phoneNumber: string;
				birthDate: Date;
				city: string;
				district: string;
				isAvailable?: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

	}

	export namespace WorkerSkills {

		export namespace GetWorkerSkills {
			export const RequestPath = AppConfig.HirovoUrl + '/WorkerSkills/GetWorkerSkills';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				languageCode: string;
			}
			export interface IResponseModel {
				skillId: Guid;
				name: string;
				translatedName: string;
				addedAt: Date;
			}
		}

		export namespace GetWorkersBySkill {
			export const RequestPath = AppConfig.HirovoUrl + '/WorkerSkills/GetWorkersBySkill';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				skillId: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				userId: Guid;
				firstName: string;
				surname: string;
				addedAt: Date;
				bucketId: string;
			}
		}

		export namespace RemoveSkill {
			export const RequestPath = AppConfig.HirovoUrl + '/WorkerSkills/RemoveSkill';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				skillId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				skillId: Guid;
				removedAt: Date;
			}
		}

		export namespace AddSkill {
			export const RequestPath = AppConfig.HirovoUrl + '/WorkerSkills/AddSkill';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				skillId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				skillId: Guid;
				skillName: string;
				createdAt: Date;
			}
		}

	}

	export namespace Users {

		export namespace UpdateLocationPreference {
			export const RequestPath = AppConfig.HirovoUrl + '/Users/UpdateLocationPreference';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				visibilityRadiusKm: Double;
			}
			export interface IResponseModel {
				userId: Guid;
				visibilityRadiusKm: Double;
				success: boolean;
			}
		}

		export namespace UpdateFcmToken {
			export const RequestPath = AppConfig.HirovoUrl + '/Users/UpdateFcmToken';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				fcmToken: string;
				deviceInfo: string;
			}
			export interface IResponseModel {
				userId: Guid;
				success: boolean;
			}
		}

	}

	export namespace DetailProfile {

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/DetailProfile/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				email: string;
				phoneNumber: string;
				city: string;
				district: string;
				description: string;
				birthDate: Date;
				isAvailable: boolean;
				bucketId: string;
			}
		}

	}

	export namespace AllProfile {

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/AllProfile/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				email: string;
				phoneNumber: string;
				city: string;
				district: string;
				description: string;
				birthDate: Date;
				isAvailable: boolean;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				createdAt: Date;
			}
		}

	}

	export namespace UpdateProfile {

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/UpdateProfile/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				firstName: string;
				surname: string;
				email: string;
				phoneNumber: string;
				city: string;
				district: string;
				description: string;
				birthDate: Date;
				isAvailable: boolean;
				bucketId: string;
			}
			export interface IResponseModel {
				userId: Guid;
			}
		}

	}

	export namespace DeleteProfile {

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/DeleteProfile/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

	}

	export namespace Roles {

		export namespace UIDC {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/UIDC';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				commands: IUidcCommands;
			}
			export interface IUidcCommands {
				edit: boolean;
				delete: boolean;
				unDelete: boolean;
			}
		}

		export namespace Pick {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				isDeleted: boolean;
				createdAt: Date;
				updatedAt?: Date;
				deletedAt?: Date;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				isDeleted: boolean;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
				companyId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				isDeleted: boolean;
				companyId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/Roles/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				name: string;
				companyId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
			}
		}

	}

	export namespace Resources {

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Resources/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				roleId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				isUsing: boolean;
			}
		}

	}

	export namespace RelUserRoles {

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/RelUserRoles/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				roleIds: Guid[];
				userId: Guid;
				companyId: Guid;
			}
			export interface IResponseModel {
				isEverythingOk: boolean;
			}
		}

	}

	export namespace RelRoleResources {

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/RelRoleResources/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				resoruceIds: Guid[];
				roleId: Guid;
			}
			export interface IResponseModel {
				isEverythingOk: boolean;
			}
		}

	}

	export namespace UserLevels {

		export namespace MyLevel {
			export const RequestPath = AppConfig.HirovoUrl + '/UserLevels/MyLevel';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				currentLevel: number;
				levelTitle: string;
				totalPoints: number;
				currentLevelProgress: number;
				pointsToNextLevel: number;
				loginStreak: number;
				nextLevelTitle: string;
			}
		}

		export namespace Leaderboard {
			export const RequestPath = AppConfig.HirovoUrl + '/UserLevels/Leaderboard';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				period: string;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				rank: number;
				userId: Guid;
				userName: string;
				userPhotoUrl: string;
				level: number;
				levelTitle: string;
				totalPoints: number;
				loginStreak: number;
			}
		}

		export namespace RecordLogin {
			export const RequestPath = AppConfig.HirovoUrl + '/UserLevels/RecordLogin';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				pointsEarned: number;
				newStreak: number;
				streakBonus?: number;
				levelUp: ILevelUpModel;
			}
			export interface ILevelUpModel {
				newLevel: number;
				newTitle: string;
			}
		}

	}

	export namespace UserFollows {

		export namespace IsFollowing {
			export const RequestPath = AppConfig.HirovoUrl + '/UserFollows/IsFollowing';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				followedUserId: Guid;
			}
			export interface IResponseModel {
				isFollowing: boolean;
				followId?: Guid;
			}
		}

		export namespace Following {
			export const RequestPath = AppConfig.HirovoUrl + '/UserFollows/Following';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				followedUserId: Guid;
				followedName: string;
				followedPhotoUrl: string;
				followedAt: Date;
			}
		}

		export namespace Followers {
			export const RequestPath = AppConfig.HirovoUrl + '/UserFollows/Followers';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				followerUserId: Guid;
				followerName: string;
				followerPhotoUrl: string;
				followedAt: Date;
			}
		}

		export namespace FollowCounts {
			export const RequestPath = AppConfig.HirovoUrl + '/UserFollows/FollowCounts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				followerCount: number;
				followingCount: number;
			}
		}

		export namespace Unfollow {
			export const RequestPath = AppConfig.HirovoUrl + '/UserFollows/Unfollow';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				followedUserId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Follow {
			export const RequestPath = AppConfig.HirovoUrl + '/UserFollows/Follow';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				followedUserId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace UserDiscoverys {

		export namespace SuggestedFollows {
			export const RequestPath = AppConfig.HirovoUrl + '/UserDiscoverys/SuggestedFollows';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				userId: Guid;
				displayName: string;
				mutualFollowCount: number;
			}
		}

		export namespace SimilarSkills {
			export const RequestPath = AppConfig.HirovoUrl + '/UserDiscoverys/SimilarSkills';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				userId: Guid;
				displayName: string;
				sharedSkillCount: number;
				sharedSkills: string[];
				isFollowing: boolean;
			}
		}

		export namespace NearbyUsers {
			export const RequestPath = AppConfig.HirovoUrl + '/UserDiscoverys/NearbyUsers';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				radiusKm: Double;
			}
			export interface IResponseModel {
				userId: Guid;
				displayName: string;
				city: string;
				district: string;
				distanceKm: Double;
				isFollowing: boolean;
			}
		}

	}

	export namespace SuccessStories {

		export namespace Featured {
			export const RequestPath = AppConfig.HirovoUrl + '/SuccessStories/Featured';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				authorName: string;
				authorPhotoUrl: string;
				title: string;
				contentPreview: string;
				photoUrl: string;
				jobTitle: string;
				likeCount: number;
				createdAt: Date;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/SuccessStories/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				id: Guid;
				authorName: string;
				authorPhotoUrl: string;
				title: string;
				contentPreview: string;
				photoUrl: string;
				jobTitle: string;
				likeCount: number;
				createdAt: Date;
				isFeatured: boolean;
			}
		}

		export namespace Like {
			export const RequestPath = AppConfig.HirovoUrl + '/SuccessStories/Like';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				storyId: Guid;
			}
			export interface IResponseModel {
				newLikeCount: number;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/SuccessStories/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				title: string;
				content: string;
				jobApplicationId?: Guid;
				photoUrl: string;
			}
			export interface IResponseModel {
				id: Guid;
				pointsEarned: number;
			}
		}

	}

	export namespace Subscriptions {

		export namespace GetPlanDetail {
			export const RequestPath = AppConfig.HirovoUrl + '/Subscriptions/GetPlanDetail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				hasActivePlan: boolean;
				plan?: Enums.SubscriptionPlan;
				startDate?: Date;
				endDate?: Date;
				daysLeft?: number;
			}
		}

		export namespace UpgradePlan {
			export const RequestPath = AppConfig.HirovoUrl + '/Subscriptions/UpgradePlan';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				newPlan: Enums.SubscriptionPlan;
			}
			export interface IResponseModel {
				userId: Guid;
				upgradedTo: string;
				startedAt: Date;
				expiresAt: Date;
			}
		}

		export namespace StartTrial {
			export const RequestPath = AppConfig.HirovoUrl + '/Subscriptions/StartTrial';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				startedAt: Date;
				expiresAt: Date;
				planType: string;
			}
		}

	}

	export namespace SocialPosts {

		export namespace UserPosts {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/UserPosts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
				sharedJob: ISharedJobModel;
				originalPost: IRepostModel;
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
			export interface ISharedJobModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
			}
			export interface IRepostModel {
				id: Guid;
				content: string;
				author: IAuthorModel;
			}
		}

		export namespace Trending {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Trending';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
				sharedJob: ISharedJobModel;
				originalPost: IRepostModel;
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
			export interface ISharedJobModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
			}
			export interface IRepostModel {
				id: Guid;
				content: string;
				author: IAuthorModel;
			}
		}

		export namespace PostDetail {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/PostDetail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				viewCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
				sharedJob: ISharedJobModel;
				originalPost: IRepostModel;
				comments: ICommentModel[];
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
			export interface ISharedJobModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
			}
			export interface IRepostModel {
				id: Guid;
				content: string;
				author: IAuthorModel;
			}
			export interface ICommentModel {
				id: Guid;
				content: string;
				createdAt: Date;
				likeCount: number;
				isLikedByMe: boolean;
				parentCommentId?: Guid;
				author: IAuthorModel;
			}
		}

		export namespace Popular {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Popular';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
				sharedJob: ISharedJobModel;
				originalPost: IRepostModel;
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
			export interface ISharedJobModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
			}
			export interface IRepostModel {
				id: Guid;
				content: string;
				author: IAuthorModel;
			}
		}

		export namespace MyPosts {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/MyPosts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
				sharedJob: ISharedJobModel;
				originalPost: IRepostModel;
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
			export interface ISharedJobModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
			}
			export interface IRepostModel {
				id: Guid;
				content: string;
				author: IAuthorModel;
			}
		}

		export namespace Feed {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Feed';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
				sharedJob: ISharedJobModel;
				originalPost: IRepostModel;
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
			export interface ISharedJobModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
			}
			export interface IRepostModel {
				id: Guid;
				content: string;
				author: IAuthorModel;
			}
		}

		export namespace Unlike {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Unlike';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				postId?: Guid;
				commentId?: Guid;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

		export namespace Repost {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Repost';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				originalPostId: Guid;
				content: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Like {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Like';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				postId?: Guid;
				commentId?: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				content: string;
				type: Enums.SocialPostType;
				sharedJobId?: Guid;
				sharedForumPostId?: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Comment {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialPosts/Comment';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				postId: Guid;
				content: string;
				parentCommentId?: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace SocialGroups {

		export namespace MyGroups {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/MyGroups';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				description: string;
				iconUrl: string;
				type: Enums.SocialGroupType;
				memberCount: number;
				postCount: number;
				createdAt: Date;
				isMember: boolean;
				creator: ICreatorModel;
			}
			export interface ICreatorModel {
				id: Guid;
				displayName: string;
			}
		}

		export namespace Members {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Members';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				groupId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				displayName: string;
				role: Enums.GroupMemberRole;
				joinedAt: Date;
			}
		}

		export namespace GroupPosts {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/GroupPosts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				groupId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				content: string;
				type: Enums.SocialPostType;
				createdAt: Date;
				likeCount: number;
				commentCount: number;
				shareCount: number;
				isLikedByMe: boolean;
				author: IAuthorModel;
			}
			export interface IAuthorModel {
				id: Guid;
				displayName: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				description: string;
				iconUrl: string;
				type: Enums.SocialGroupType;
				memberCount: number;
				postCount: number;
				createdAt: Date;
				isMember: boolean;
				myRole?: Enums.GroupMemberRole;
				creator: ICreatorModel;
				recentMembers: IRecentMemberModel[];
			}
			export interface ICreatorModel {
				id: Guid;
				displayName: string;
			}
			export interface IRecentMemberModel {
				id: Guid;
				displayName: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				searchTerm: string;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				description: string;
				iconUrl: string;
				type: Enums.SocialGroupType;
				memberCount: number;
				postCount: number;
				createdAt: Date;
				isMember: boolean;
				creator: ICreatorModel;
			}
			export interface ICreatorModel {
				id: Guid;
				displayName: string;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
				description: string;
				iconUrl: string;
				type: Enums.SocialGroupType;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Leave {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Leave';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				groupId: Guid;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

		export namespace Join {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Join';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				groupId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				name: string;
				description: string;
				iconUrl: string;
				type: Enums.SocialGroupType;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace AddAdmin {
			export const RequestPath = AppConfig.HirovoUrl + '/SocialGroups/AddAdmin';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				groupId: Guid;
				userId: Guid;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

	}

	export namespace Skills {

		export namespace Pick {
			export const RequestPath = AppConfig.HirovoUrl + '/Skills/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
				languageCode: string;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Skills/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				languageCode: string;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				category: string;
			}
		}

		export namespace SeedAndTranslate {
			export const RequestPath = AppConfig.HirovoUrl + '/Skills/SeedAndTranslate';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				seedCount: number;
				translationCount: number;
				processedAt: Date;
				message: string;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/Skills/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				key: string;
				languageCode: string;
				translatedName: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace SkillEndorsements {

		export namespace GetEndorsements {
			export const RequestPath = AppConfig.HirovoUrl + '/SkillEndorsements/GetEndorsements';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				skillId: Guid;
				skillName: string;
				endorsementCount: number;
				endorsers: IEndorserModel[];
			}
			export interface IEndorserModel {
				userId: Guid;
				name: string;
				photoUrl: string;
			}
		}

		export namespace RemoveEndorsement {
			export const RequestPath = AppConfig.HirovoUrl + '/SkillEndorsements/RemoveEndorsement';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				endorsedUserId: Guid;
				skillId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Endorse {
			export const RequestPath = AppConfig.HirovoUrl + '/SkillEndorsements/Endorse';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				endorsedUserId: Guid;
				skillId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Review {

		export namespace Pick {
			export const RequestPath = AppConfig.HirovoUrl + '/Review/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				jobId: Guid;
				jobApplicationId: Guid;
				reviewerId: Guid;
				reviewerName: string;
				reviewedUserId: Guid;
				reviewedUserName: string;
				reviewerType: Enums.ReviewerType;
				rating: number;
				comment: string;
				createdAt: Date;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/Review/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId?: Guid;
			}
			export interface IResponseModel {
				summary: IUserReviewSummaryModel;
				reviews: IReviewItemModel[];
			}
			export interface IUserReviewSummaryModel {
				userId: Guid;
				averageRating: __ERROR_TYPE_NOT_HANDLED__;
				totalReviews: number;
				fiveStarCount: number;
				fourStarCount: number;
				threeStarCount: number;
				twoStarCount: number;
				oneStarCount: number;
			}
			export interface IReviewItemModel {
				id: Guid;
				jobId: Guid;
				jobTitle: string;
				reviewerId: Guid;
				reviewerName: string;
				reviewerType: Enums.ReviewerType;
				rating: number;
				comment: string;
				createdAt: Date;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Review/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				jobId: Guid;
				jobTitle: string;
				reviewerId: Guid;
				reviewerName: string;
				reviewedUserId: Guid;
				reviewedUserName: string;
				reviewerType: Enums.ReviewerType;
				rating: number;
				comment: string;
				createdAt: Date;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/Review/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				rating: number;
				comment: string;
			}
			export interface IResponseModel {
				id: Guid;
				rating: number;
				updatedAt: Date;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Review/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				deletedAt: Date;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/Review/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobApplicationId: Guid;
				rating: number;
				comment: string;
			}
			export interface IResponseModel {
				id: Guid;
				rating: number;
				createdAt: Date;
			}
		}

	}

	export namespace Referrals {

		export namespace GetUserReferrals {
			export const RequestPath = AppConfig.HirovoUrl + '/Referrals/GetUserReferrals';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				writerName: string;
				writerPhotoUrl: string;
				jobTitle: string;
				content: string;
				type: Enums.ReferralType;
				createdAt: Date;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/Referrals/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				content: string;
				isPublic: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Referrals/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/Referrals/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				receiverUserId: Guid;
				jobApplicationId: Guid;
				content: string;
				isPublic: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace ProfileViews {

		export namespace Stats {
			export const RequestPath = AppConfig.HirovoUrl + '/ProfileViews/Stats';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				period: string;
			}
			export interface IResponseModel {
				totalViews: number;
				uniqueViewers: number;
				viewsBySource: IViewsBySourceModel;
				trend: Double;
			}
			export interface IViewsBySourceModel {
				search: number;
				jobApplication: number;
				recommendation: number;
				direct: number;
			}
		}

		export namespace Recent {
			export const RequestPath = AppConfig.HirovoUrl + '/ProfileViews/Recent';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				viewerUserId: Guid;
				viewerName: string;
				viewerPhotoUrl: string;
				source: Enums.ProfileViewSource;
				viewedAt: Date;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/ProfileViews/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				viewedUserId: Guid;
				source: Enums.ProfileViewSource;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace NotificationPreferences {

		export namespace Get {
			export const RequestPath = AppConfig.HirovoUrl + '/NotificationPreferences/Get';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				emailNotifications: boolean;
				smsNotifications: boolean;
				pushNotifications: boolean;
				jobAlerts: boolean;
				messageAlerts: boolean;
				applicationStatusAlerts: boolean;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/NotificationPreferences/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				emailNotifications: boolean;
				smsNotifications: boolean;
				pushNotifications: boolean;
				jobAlerts: boolean;
				messageAlerts: boolean;
				applicationStatusAlerts: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Messagings {

		export namespace GetUnreadCount {
			export const RequestPath = AppConfig.HirovoUrl + '/Messagings/GetUnreadCount';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalUnreadCount: number;
				conversations: IConversationUnreadItem[];
			}
			export interface IConversationUnreadItem {
				id: Guid;
				count: number;
			}
		}

		export namespace GetMessages {
			export const RequestPath = AppConfig.HirovoUrl + '/Messagings/GetMessages';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				conversationId: Guid;
				pageRequest: IXPageRequest;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				senderId: Guid;
				senderName: string;
				content: string;
				isRead: boolean;
				createdAt: Date;
				isOwn: boolean;
			}
		}

		export namespace GetConversations {
			export const RequestPath = AppConfig.HirovoUrl + '/Messagings/GetConversations';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				otherUserName: string;
				otherUserId: Guid;
				jobTitle: string;
				lastMessage: string;
				lastMessageAt?: Date;
				unreadCount: number;
			}
		}

		export namespace SendMessage {
			export const RequestPath = AppConfig.HirovoUrl + '/Messagings/SendMessage';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				conversationId?: Guid;
				jobApplicationId?: Guid;
				recipientUserId?: Guid;
				content: string;
			}
			export interface IResponseModel {
				messageId: Guid;
				conversationId: Guid;
				sentAt: Date;
			}
		}

		export namespace MarkAsRead {
			export const RequestPath = AppConfig.HirovoUrl + '/Messagings/MarkAsRead';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				conversationId: Guid;
			}
			export interface IResponseModel {
				markedCount: number;
			}
		}

	}

	export namespace Mentions {

		export namespace MyMentions {
			export const RequestPath = AppConfig.HirovoUrl + '/Mentions/MyMentions';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				sourceType: Enums.MentionSourceType;
				sourceId: Guid;
				createdAt: Date;
				mentioner: IMentionerModel;
			}
			export interface IMentionerModel {
				id: Guid;
				displayName: string;
			}
		}

	}

	export namespace Location {

		export namespace GetNearbyWorkers {
			export const RequestPath = AppConfig.HirovoUrl + '/Location/GetNearbyWorkers';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				companyId: Guid;
				latitude: Double;
				longitude: Double;
				limit: number;
			}
			export interface IResponseModel {
				userId: Guid;
				fullName: string;
				distanceInKm: Double;
			}
		}

		export namespace GetNearbyJobs {
			export const RequestPath = AppConfig.HirovoUrl + '/Location/GetNearbyJobs';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				latitude: Double;
				longitude: Double;
				companyId: Guid;
				limit: number;
				customRadiusKm?: Double;
			}
			export interface IResponseModel {
				jobId: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				distanceInKm: Double;
				endDate: Date;
			}
		}

		export namespace SetLocation {
			export const RequestPath = AppConfig.HirovoUrl + '/Location/SetLocation';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				latitude: Double;
				longitude: Double;
				companyId: Guid;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

	}

	export namespace Jobs {

		export namespace SalaryComparison {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/SalaryComparison';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				skillIds: Guid[];
				city: string;
				jobType?: Enums.HirovoJobType;
			}
			export interface IResponseModel {
				averageSalary: Double;
				medianSalary: Double;
				minSalary: Double;
				maxSalary: Double;
				sampleSize: number;
				byCity: ICitySalaryModel[];
				byJobType: IJobTypeSalaryModel[];
				trend: ITrendModel;
			}
			export interface ICitySalaryModel {
				city: string;
				averageSalary: Double;
				jobCount: number;
			}
			export interface IJobTypeSalaryModel {
				type: Enums.HirovoJobType;
				averageSalary: Double;
				jobCount: number;
			}
			export interface ITrendModel {
				lastMonth: Double;
				thisMonth: Double;
				changePercentage: Double;
			}
		}

		export namespace Recommended {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/Recommended';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
				maxDistance?: Double;
				languageCode: string;
			}
			export interface IResponseModel {
				jobId: Guid;
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				city: string;
				district: string;
				matchScore: Double;
				matchReasons: string[];
				distanceKm?: Double;
				skills: ISkillModel[];
				endDate: Date;
			}
			export interface ISkillModel {
				id: Guid;
				name: string;
			}
		}

		export namespace Pick {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
				languageCode: string;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				employerId: Guid;
				employerDisplayName: string;
				latitude: Double;
				longitude: Double;
				notifyRadiusKm: Double;
				endDate: Date;
				skills: ISkillModel[];
			}
			export interface ISkillModel {
				id: Guid;
				name: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				languageCode: string;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
				minSalary?: __ERROR_TYPE_NOT_HANDLED__;
				maxSalary?: __ERROR_TYPE_NOT_HANDLED__;
				userLatitude?: Double;
				userLongitude?: Double;
				sortByDistance: boolean;
				statusFilter?: Enums.HirovoJobStatus;
				searchTerm: string;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				endDate: Date;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				hirovoEmployer_Id: Guid;
				application: number;
				skills: ISkillModel[];
			}
			export interface ISkillModel {
				id: Guid;
				name: string;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				latitude: Double;
				longitude: Double;
				notifyRadiusKm: Double;
				skillIds: Guid[];
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				employerId: Guid;
				latitude: Double;
				longitude: Double;
				notifyRadiusKm: Double;
				companyId: Guid;
				skillIds: Guid[];
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace JobSwipes {

		export namespace Stats {
			export const RequestPath = AppConfig.HirovoUrl + '/JobSwipes/Stats';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalSwipes: number;
				rightSwipes: number;
				leftSwipes: number;
				superSwipes: number;
				applicationsFromSwipe: number;
			}
		}

		export namespace GetCards {
			export const RequestPath = AppConfig.HirovoUrl + '/JobSwipes/GetCards';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				count: number;
				maxDistance?: Double;
				languageCode: string;
			}
			export interface IResponseModel {
				jobId: Guid;
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				city: string;
				district: string;
				employerName: string;
				employerPhotoUrl: string;
				matchScore: Double;
				distanceKm?: Double;
				matchingSkills: string[];
			}
		}

		export namespace Swipe {
			export const RequestPath = AppConfig.HirovoUrl + '/JobSwipes/Swipe';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
				direction: Enums.SwipeDirection;
			}
			export interface IResponseModel {
				id: Guid;
				action: string;
				pointsEarned: number;
				matchMessage: string;
			}
		}

	}

	export namespace JobReports {

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/JobReports/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				jobId: Guid;
				jobTitle: string;
				reporterName: string;
				reason: Enums.JobReportReason;
				status: Enums.JobReportStatus;
				createdAt: Date;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/JobReports/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
				reason: Enums.JobReportReason;
				description: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace JobApplications {

		export namespace Pick {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobApplicationId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				status: Enums.ApplicationStatus;
				appliedAt: Date;
				job: IJobInfoModel;
				worker: IWorkerInfoModel;
			}
			export interface IJobInfoModel {
				id: Guid;
				title: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				endDate: Date;
			}
			export interface IWorkerInfoModel {
				id: Guid;
				fullName: string;
				phoneNumber: string;
				city: string;
				district: string;
			}
		}

		export namespace AppliedJobs {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/AppliedJobs';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				workerId: Guid;
			}
			export interface IResponseModel {
				jobId: Guid;
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				appliedAt: Date;
				endDate: Date;
				applicationStatus: Enums.ApplicationStatus;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				jobId: Guid;
				workerId: Guid;
				status: Enums.ApplicationStatus;
				appliedAt: Date;
				endDate: Date;
				jobTitle: string;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isAvailable?: boolean;
				displayName: string;
				description: string;
				bucketId: string;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobApplicationId: Guid;
				jobId: Guid;
				workerId: Guid;
				appliedAt?: Date;
				companyId: Guid;
			}
			export interface IResponseModel {
				jobApplicationId: Guid;
			}
		}

		export namespace UpdateStatus {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/UpdateStatus';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobApplicationId: Guid;
				status: Enums.ApplicationStatus;
			}
			export interface IResponseModel {
				jobApplicationId: Guid;
				status: string;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobApplicationId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/JobApplications/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
				workerId: Guid;
				companyId: Guid;
			}
			export interface IResponseModel {
				jobApplicationId: Guid;
			}
		}

	}

	export namespace Invites {

		export namespace Stats {
			export const RequestPath = AppConfig.HirovoUrl + '/Invites/Stats';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalInvitesSent: number;
				successfulInvites: number;
				totalPointsEarned: number;
				activeCode: string;
			}
		}

		export namespace MyInvites {
			export const RequestPath = AppConfig.HirovoUrl + '/Invites/MyInvites';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				items: IInviteItemModel[];
				totalCount: number;
				totalPointsEarned: number;
			}
			export interface IInviteItemModel {
				code: string;
				invitedUserName: string;
				status: Enums.InviteStatus;
				pointsEarned?: number;
				createdAt: Date;
				usedAt?: Date;
			}
		}

		export namespace RedeemCode {
			export const RequestPath = AppConfig.HirovoUrl + '/Invites/RedeemCode';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				code: string;
			}
			export interface IResponseModel {
				success: boolean;
				welcomePoints: number;
				inviterName: string;
			}
		}

		export namespace GenerateCode {
			export const RequestPath = AppConfig.HirovoUrl + '/Invites/GenerateCode';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				code: string;
				shareUrl: string;
				expiresAt: Date;
				pointsReward: number;
			}
		}

	}

	export namespace Forums {

		export namespace Posts {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/Posts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				categoryId?: Guid;
				searchTerm: string;
				sortBy: string;
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				contentPreview: string;
				authorName: string;
				authorPhotoUrl: string;
				categoryName: string;
				viewCount: number;
				commentCount: number;
				upvoteCount: number;
				createdAt: Date;
				hasAcceptedAnswer: boolean;
			}
		}

		export namespace PostDetail {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/PostDetail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				postId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				content: string;
				authorName: string;
				authorPhotoUrl: string;
				categoryName: string;
				viewCount: number;
				commentCount: number;
				upvoteCount: number;
				downvoteCount: number;
				isPinned: boolean;
				isLocked: boolean;
				createdAt: Date;
				hasAcceptedAnswer: boolean;
				comments: ICommentModel[];
				userVote?: Enums.VoteType;
			}
			export interface ICommentModel {
				id: Guid;
				content: string;
				authorName: string;
				authorPhotoUrl: string;
				upvoteCount: number;
				downvoteCount: number;
				isAcceptedAnswer: boolean;
				parentCommentId?: Guid;
				createdAt: Date;
				userVote?: Enums.VoteType;
			}
		}

		export namespace MyPosts {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/MyPosts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				contentPreview: string;
				categoryName: string;
				viewCount: number;
				commentCount: number;
				upvoteCount: number;
				createdAt: Date;
				hasAcceptedAnswer: boolean;
			}
		}

		export namespace Categories {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/Categories';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				description: string;
				iconUrl: string;
				sortOrder: number;
				parentCategoryId?: Guid;
			}
		}

		export namespace Vote {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/Vote';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				postId?: Guid;
				commentId?: Guid;
				type: Enums.VoteType;
			}
			export interface IResponseModel {
				newUpvoteCount: number;
				newDownvoteCount: number;
			}
		}

		export namespace CreatePost {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/CreatePost';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				categoryId: Guid;
				title: string;
				content: string;
			}
			export interface IResponseModel {
				id: Guid;
				pointsEarned: number;
			}
		}

		export namespace CreateComment {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/CreateComment';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				postId: Guid;
				content: string;
				parentCommentId?: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				pointsEarned: number;
			}
		}

		export namespace AcceptAnswer {
			export const RequestPath = AppConfig.HirovoUrl + '/Forums/AcceptAnswer';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				commentId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				pointsEarned: number;
			}
		}

	}

	export namespace Favorites {

		export namespace Check {
			export const RequestPath = AppConfig.HirovoUrl + '/Favorites/Check';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
			}
			export interface IResponseModel {
				isFavorited: boolean;
				favoriteId?: Guid;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Favorites/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				languageCode: string;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				jobId: Guid;
				jobTitle: string;
				jobSalary: __ERROR_TYPE_NOT_HANDLED__;
				jobType: Enums.HirovoJobType;
				favoritedAt: Date;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Favorites/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				deletedAt: Date;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/Favorites/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				jobId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				jobId: Guid;
				createdAt: Date;
			}
		}

	}

	export namespace Employers {

		export namespace TransparencyScore {
			export const RequestPath = AppConfig.HirovoUrl + '/Employers/TransparencyScore';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				employerUserId: Guid;
			}
			export interface IResponseModel {
				overallScore: number;
				breakdown: IBreakdownModel;
				badges: string[];
				totalJobsPosted: number;
				totalHires: number;
			}
			export interface IBreakdownModel {
				responseRate: number;
				responseTime: Double;
				completionRate: number;
				reviewScore: Double;
				jobDetailQuality: number;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/Employers/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				email: string;
				phoneNumber: string;
				city: string;
				district: string;
				description: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Employers/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				description: string;
				salary: __ERROR_TYPE_NOT_HANDLED__;
				type: Enums.HirovoJobType;
				status: Enums.HirovoJobStatus;
				createdAt: Date;
			}
		}

		export namespace UpdateProfile {
			export const RequestPath = AppConfig.HirovoUrl + '/Employers/UpdateProfile';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				phoneNumber: string;
				city: string;
				district: string;
				description: string;
				bucketId: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/Employers/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

	}

	export namespace EmployerFollows {

		export namespace MyFollows {
			export const RequestPath = AppConfig.HirovoUrl + '/EmployerFollows/MyFollows';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				employerUserId: Guid;
				employerName: string;
				employerPhotoUrl: string;
				activeJobCount: number;
				followedAt: Date;
			}
		}

		export namespace IsFollowing {
			export const RequestPath = AppConfig.HirovoUrl + '/EmployerFollows/IsFollowing';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				employerUserId: Guid;
			}
			export interface IResponseModel {
				isFollowing: boolean;
				followId?: Guid;
			}
		}

		export namespace FollowerCount {
			export const RequestPath = AppConfig.HirovoUrl + '/EmployerFollows/FollowerCount';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				employerUserId: Guid;
			}
			export interface IResponseModel {
				followerCount: number;
			}
		}

		export namespace Unfollow {
			export const RequestPath = AppConfig.HirovoUrl + '/EmployerFollows/Unfollow';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				employerUserId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Follow {
			export const RequestPath = AppConfig.HirovoUrl + '/EmployerFollows/Follow';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				employerUserId: Guid;
				notifyOnNewJob: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Documents {

		export namespace CheckAccessCode {
			export const RequestPath = AppConfig.HirovoUrl + '/Documents/CheckAccessCode';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				documentId: Guid;
				fileAccessCode: Guid;
				companyId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				isEverthingOk: boolean;
			}
		}

	}

	export namespace Dashboards {

		export namespace WorkerStats {
			export const RequestPath = AppConfig.HirovoUrl + '/Dashboards/WorkerStats';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalApplications: number;
				pendingApplications: number;
				acceptedApplications: number;
				rejectedApplications: number;
				cancelledApplications: number;
				averageRating: Double;
				totalReviews: number;
			}
		}

		export namespace PlatformStats {
			export const RequestPath = AppConfig.HirovoUrl + '/Dashboards/PlatformStats';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				startDate?: Date;
				endDate?: Date;
			}
			export interface IResponseModel {
				totalJobs: number;
				activeJobs: number;
				closedJobs: number;
				expiredJobs: number;
				totalWorkers: number;
				totalEmployers: number;
				totalApplications: number;
				acceptedApplications: number;
				rejectedApplications: number;
				pendingApplications: number;
				totalReviews: number;
				averageRating: Double;
				totalMessages: number;
				totalConversations: number;
				newJobsThisMonth: number;
				newUsersThisMonth: number;
			}
		}

		export namespace EmployerStats {
			export const RequestPath = AppConfig.HirovoUrl + '/Dashboards/EmployerStats';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalJobsPosted: number;
				activeJobs: number;
				closedJobs: number;
				filledJobs: number;
				totalApplicationsReceived: number;
				pendingApplications: number;
				acceptedApplications: number;
				rejectedApplications: number;
				averageRating: Double;
				totalReviews: number;
			}
		}

	}

	export namespace Contents {

		export namespace Pages {
			export const RequestPath = AppConfig.HirovoUrl + '/Contents/Pages';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				items: IPageItem[];
			}
			export interface IPageItem {
				id: number;
				title: string;
				slug: string;
				content: string;
				publishedAt: Date;
			}
		}

		export namespace BlogPost {
			export const RequestPath = AppConfig.HirovoUrl + '/Contents/BlogPost';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: number;
			}
			export interface IResponseModel {
				id: number;
				title: string;
				content: string;
				featuredImageUrl: string;
				author: string;
				publishedAt: Date;
				categories: string[];
				readTimeMinutes: number;
			}
		}

		export namespace BlogPosts {
			export const RequestPath = AppConfig.HirovoUrl + '/Contents/BlogPosts';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				page: number;
				pageSize: number;
				category: string;
				searchTerm: string;
			}
			export interface IResponseModel {
				items: IBlogPostItem[];
				totalCount: number;
			}
			export interface IBlogPostItem {
				id: number;
				title: string;
				excerpt: string;
				featuredImageUrl: string;
				author: string;
				publishedAt: Date;
				categories: string[];
				readTimeMinutes: number;
			}
		}

	}

	export namespace Careers {

		export namespace TrendingSkills {
			export const RequestPath = AppConfig.HirovoUrl + '/Careers/TrendingSkills';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				period: string;
			}
			export interface IResponseModel {
				skills: ITrendingSkillItem[];
			}
			export interface ITrendingSkillItem {
				skillId: Guid;
				name: string;
				jobCount: number;
				growthPercentage: Double;
			}
		}

		export namespace SkillGap {
			export const RequestPath = AppConfig.HirovoUrl + '/Careers/SkillGap';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				totalUserSkills: number;
				missingSkills: IGapItem[];
				recommendations: string[];
			}
			export interface IGapItem {
				skillId: Guid;
				name: string;
				demandCount: number;
				reason: string;
			}
		}

		export namespace Roadmap {
			export const RequestPath = AppConfig.HirovoUrl + '/Careers/Roadmap';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				currentSkills: ICurrentSkillItem[];
				suggestedSkills: ISuggestedSkillItem[];
				careerPaths: ICareerPathItem[];
			}
			export interface ICurrentSkillItem {
				skillId: Guid;
				name: string;
				endorsementCount: number;
				isAssessed: boolean;
			}
			export interface ISuggestedSkillItem {
				skillId: Guid;
				name: string;
				demandScore: number;
				jobCount: number;
			}
			export interface ICareerPathTranslationItem {
				languageCode: string;
				title: string;
			}
			export interface ICareerPathItem {
				title: string;
				matchPercentage: number;
				requiredSkills: string[];
				missingSkills: string[];
				translations: ICareerPathTranslationItem[];
			}
		}

	}

	export namespace CareerPaths {

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/CareerPaths/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				title: string;
				description: string;
				iconUrl: string;
				sortOrder: number;
				isActive: boolean;
				skills: ISkillItem[];
				translations: ITranslationItem[];
			}
			export interface ISkillItem {
				skillId: Guid;
				name: string;
			}
			export interface ITranslationItem {
				languageCode: string;
				title: string;
				description: string;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.HirovoUrl + '/CareerPaths/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				title: string;
				description: string;
				iconUrl: string;
				sortOrder: number;
				isActive: boolean;
				skillIds: Guid[];
				translations: ITranslationItem[];
			}
			export interface ITranslationItem {
				languageCode: string;
				title: string;
				description: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.HirovoUrl + '/CareerPaths/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.HirovoUrl + '/CareerPaths/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				title: string;
				description: string;
				iconUrl: string;
				sortOrder: number;
				skillIds: Guid[];
				translations: ITranslationItem[];
			}
			export interface ITranslationItem {
				languageCode: string;
				title: string;
				description: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Assessments {

		export namespace UserBadges {
			export const RequestPath = AppConfig.HirovoUrl + '/Assessments/UserBadges';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId?: Guid;
			}
			export interface IResponseModel {
				items: IBadgeItem[];
			}
			export interface IBadgeItem {
				skillId: Guid;
				skillName: string;
				difficulty: number;
				score: number;
				completedAt: Date;
			}
		}

		export namespace Start {
			export const RequestPath = AppConfig.HirovoUrl + '/Assessments/Start';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				assessmentId: Guid;
			}
			export interface IResponseModel {
				assessmentId: Guid;
				title: string;
				timeLimitMinutes: number;
				questions: IQuestionItem[];
			}
			export interface IQuestionItem {
				id: Guid;
				questionText: string;
				optionA: string;
				optionB: string;
				optionC: string;
				optionD: string;
				sortOrder: number;
			}
		}

		export namespace MyResults {
			export const RequestPath = AppConfig.HirovoUrl + '/Assessments/MyResults';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				items: IResultItem[];
			}
			export interface IResultItem {
				id: Guid;
				assessmentId: Guid;
				assessmentTitle: string;
				skillName: string;
				score: number;
				isPassed: boolean;
				correctAnswers: number;
				totalQuestions: number;
				timeTakenSeconds: number;
				completedAt: Date;
			}
		}

		export namespace Available {
			export const RequestPath = AppConfig.HirovoUrl + '/Assessments/Available';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				skillId?: Guid;
			}
			export interface IResponseModel {
				items: IAssessmentItem[];
			}
			export interface IAssessmentItem {
				id: Guid;
				skillId: Guid;
				skillName: string;
				title: string;
				description: string;
				difficulty: number;
				timeLimitMinutes: number;
				questionCount: number;
				passingScore: number;
				bestScore?: number;
				isPassed?: boolean;
				lastAttemptAt?: Date;
			}
		}

		export namespace Submit {
			export const RequestPath = AppConfig.HirovoUrl + '/Assessments/Submit';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				assessmentId: Guid;
				answers: IAnswerItem[];
				timeTakenSeconds: number;
			}
			export interface IAnswerItem {
				questionId: Guid;
				selectedOption: string;
			}
			export interface IResponseModel {
				id: Guid;
				score: number;
				isPassed: boolean;
				correctAnswers: number;
				totalQuestions: number;
				pointsEarned: number;
			}
		}

	}

	export namespace Achievements {

		export namespace MyAchievements {
			export const RequestPath = AppConfig.HirovoUrl + '/Achievements/MyAchievements';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				achievementId: Guid;
				code: string;
				name: string;
				description: string;
				iconUrl: string;
				category: Enums.AchievementCategory;
				pointsReward: number;
				earnedAt: Date;
			}
		}

		export namespace CheckProgress {
			export const RequestPath = AppConfig.HirovoUrl + '/Achievements/CheckProgress';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				newAchievements: INewAchievementModel[];
				totalPoints: number;
			}
			export interface INewAchievementModel {
				id: Guid;
				code: string;
				name: string;
				pointsReward: number;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.HirovoUrl + '/Achievements/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				id: Guid;
				code: string;
				name: string;
				description: string;
				iconUrl: string;
				category: Enums.AchievementCategory;
				requiredCount: number;
				pointsReward: number;
				isEarned: boolean;
				earnedAt?: Date;
				currentProgress: number;
			}
		}

	}

}